### ISSUE TITLE
[WIP] 2018 cleanup

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/awesome-json-datasets#188]
## Part 2

**Add**
- [ ] #180 
- [ ] Manifests e.g. https://news.google.com/_/NewsUi/manifest.json
- [ ] "[Browse](https://data.michigan.gov/browse)" section or ProTips
- [ ] [ooni probes](https://api.ooni.io/)

**Remove**
- [ ] Dead links (TBD)

**Prepare**
- [x] Choose dataset of the month for April

----

## Part 1

**Add**
- [x] Other cryptocurrencies
- [x] [USA population since 1960](http://api.worldbank.org/countries/USA/indicators/SP.POP.TOTL?per_page=5000&format=json)
- [x] Dataset of the month?

**Remove**
- [x] Cars (Broken JSON)
- [x] Browse links e.g. https://data.michigan.gov/browse
- [x] Useless Government datasets (Tariff Rates, Business Service Providers, etc)

**Comment by jdorfman** [comment]
@Mandihamza possible OSF assignment
